#!/usr/bin/env python3
import argparse
import pathlib
import typing

import pydantic
from altcos import ostree, build

import cmdlib

SR = cmdlib.import_env(cmdlib.STREAMS_ROOT_ENV)
BR = cmdlib.import_env(cmdlib.BUILDS_ROOT_ENV)

FormatMapping: typing.TypeAlias = dict[build.Format, build.Artifact]
PlatformMapping: typing.TypeAlias = dict[build.Platform, FormatMapping]
VersionMapping: typing.TypeAlias = dict[str, PlatformMapping]
StreamMapping: typing.TypeAlias = dict[str, VersionMapping]
ArchMapping: typing.TypeAlias = dict[str, StreamMapping]
BranchMapping: typing.TypeAlias = dict[ostree.Branch, ArchMapping]


class Collector:
    def __init__(self, branch: ostree.Branch) -> None:
        self.branch = branch
        self.root = pathlib.Path(BR, self.branch.value)

    def collect_artifact(self,
                         arch: ostree.Arch,
                         stream: str,
                         version: ostree.Version,
                         platform: build.Platform,
                         fmt: build.Format) -> build.Artifact:

        artifacts = [artifact for artifact in
                     self.root.glob(f"{arch}/{stream}/{version}/{platform}/{fmt}/*")]

        [location, signature, uncompressed, uncompressed_signature] = [None] * 4

        for artifact in artifacts:
            if artifact.name.endswith(".tar.gz.sig"):
                signature = artifact
            elif artifact.name.endswith(".tar.gz"):
                location = artifact
            elif artifact.name.endswith(".sig"):
                uncompressed_signature = artifact
            else:
                uncompressed = artifact

        return build.Artifact(build.Disk(location, signature, uncompressed, uncompressed_signature))

    def collect_format(self,
                       arch: ostree.Arch,
                       stream: str,
                       version: ostree.Version,
                       platform: build.Platform) -> FormatMapping:

        formats = {}
        for fmt in self.root.glob(f"{arch}/{stream}/{version}/{platform}/*"):
            fmt = build.Format(fmt.name)
            formats[fmt] = self.collect_artifact(arch, stream, version, platform, fmt)
        return formats

    def collect_platform(self,
                         arch: ostree.Arch,
                         stream: str,
                         version: ostree.Version) -> PlatformMapping:
        platforms = {}
        for platform in self.root.glob(f"{arch}/{stream}/{version}/*"):
            platform = build.Platform(platform.name)
            platforms[platform] = self.collect_format(arch, stream, version, platform)
        return platforms

    def collect_version(self,
                        arch: ostree.Arch,
                        stream: str) -> VersionMapping:
        versions = {}
        for version in self.root.glob(f"{arch}/{stream}/*"):
            version_name = f"{self.branch}_{stream}.{version.name}"
            versions[version.name] = self.collect_platform(arch,
                                                           stream,
                                                           ostree.Version.from_str(version_name))
        return versions

    def collect_stream(self, arch: ostree.Arch) -> StreamMapping:
        streams = {}
        for stream in self.root.glob(f"{arch}/*"):
            streams[stream.name] = self.collect_version(arch, stream.name)
        return streams

    def collect_arch(self) -> ArchMapping:
        architectures = {}
        for arch in self.root.glob("*"):
            arch = ostree.Arch(arch.name)
            architectures[arch.value] = self.collect_stream(arch)
        return architectures

    def collect(self) -> BranchMapping:
        return {self.branch: self.collect_arch()}


class SisyphusBuilds(pydantic.BaseModel):
    sisyphus: typing.Any


class P10Builds(pydantic.BaseModel):
    p10: typing.Any


def main() -> None:
    parser = argparse.ArgumentParser(description="Collects information on the stream.")
    parser.add_argument("branch")

    args = parser.parse_args()

    builds = {
        ostree.Branch.SISYPHUS: SisyphusBuilds,
        ostree.Branch.P10: P10Builds
    }

    branch = ostree.Branch(args.branch)
    summary = Collector(branch).collect()
    print(builds[branch].parse_obj(summary).json())


if __name__ == "__main__":
    main()
