#!/usr/bin/env python3

import argparse

import altcos
import cmdlib

SR = cmdlib.import_env(cmdlib.STREAMS_ROOT_ENV)


def main() -> None:

    parser = argparse.ArgumentParser()
    parser.add_argument("-n", "--osname",
                        choices=[*altcos.OSName],
                        default=altcos.OSName.ALTCOS.value)
    parser.add_argument("-a", "--arch",
                        choices=[*altcos.Arch],
                        required=True)
    parser.add_argument("-b", "--branch",
                        choices=[*altcos.Branch],
                        required=True)
    parser.add_argument("-s", "--substream")

    args = parser.parse_args()

    stream = altcos.Stream(SR,
                           altcos.OSName(args.osname),
                           altcos.Arch(args.arch),
                           altcos.Branch(args.branch),
                           args.substream)

    print(cmdlib.stream_to_export(stream))


if __name__ == '__main__':
    main()
