#!/usr/bin/env python3

import argparse

from altcos import ostree

import cmdlib

SR = cmdlib.import_env(cmdlib.STREAMS_ROOT_ENV)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("-n", "--osname",
                        choices=[*ostree.OSName],
                        default=ostree.OSName.ALTCOS.value)
    parser.add_argument("-a", "--arch",
                        choices=[*ostree.Arch],
                        required=True)
    parser.add_argument("-b", "--branch",
                        choices=[*ostree.Branch],
                        required=True)
    parser.add_argument("-s", "--substream")

    args = parser.parse_args()

    stream = ostree.Stream(SR,
                           ostree.OSName(args.osname),
                           ostree.Arch(args.arch),
                           ostree.Branch(args.branch),
                           args.substream)

    print(cmdlib.stream_to_export(stream))


if __name__ == '__main__':
    main()
